flags: {}

extra-package-dbs: []

system-ghc: true

packages:
    - core
    - geometry
    - probability
    - graphical

resolver: lts-19.11

extra-deps:
    - hmatrix-special-0.19.0.0

ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""

build:
  haddock-arguments:
    haddock-args:
    - --optghc=-fdefer-type-errors
