flags: {}
extra-package-dbs: []
packages:
    - core
    - geometry
    - probability
    - simulation
    - applications/kohn-lab
    - applications/mnist
    - applications/hgm
    - chart
    - chart-cairo
resolver: nightly-2018-06-02
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
