flags: {}
extra-package-dbs: []
packages:
    - core
    - geometry
    - probability
    - simulation
    - applications/neural-data
resolver: nightly-2018-12-03
extra-deps:
    - hmatrix-special-0.19.0.0
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
