flags: {}
extra-package-dbs: []
packages:
    - core
    - geometry
    - probability
    - simulation
    - applications/neural-data
resolver: lts-12.9
extra-deps:
    - Chart-1.9
    - Chart-cairo-1.9
    - singleton-typelits-0.1.0.0
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
