flags: {}
extra-package-dbs: []
packages:
    - core
    - geometry
    - probability
resolver: lts-15.0
extra-deps:
    - hmatrix-special-0.19.0.0
    - ghc-typelits-knownnat-0.7
    - ghc-typelits-natnormalise-0.7
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
build:
  haddock-arguments:
    haddock-args:
    - --optghc=-fdefer-type-errors
