flags: {}
extra-package-dbs: []
packages:
    - core
    - geometry
    - probability
    - simulation
    - applications/kohn-lab
    - applications/mnist
    - applications/hgm
resolver: lts-12.6
extra-deps:
    - Chart-1.9
    - Chart-cairo-1.9
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
