flags: {}
extra-package-dbs: []
packages:
    - core
    - geometry
    - probability
    - applications/neural-data
resolver: lts-12.25
extra-deps:
    - ghc-typelits-knownnat-0.6
    - haskell-src-exts-1.21.0
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
