flags: {}
extra-package-dbs: []
packages:
    - core
    - geometry
    - probability
    - simulation
    - applications/neural-data
resolver: lts-12.17
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
