flags: {}
extra-package-dbs: []
packages:
    - core
    - geometry
    - probability
    - simulation
    - applications/goal-plot
    - applications/neural-data
resolver: lts-12.13
extra-deps:
    - singleton-typelits-0.1.0.0
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
