flags: {}
extra-package-dbs: []
packages:
    - core
    - geometry
    - probability
    - simulation
    - applications/kohn-lab
    - applications/mnist
resolver: lts-11.8
extra-deps:
    - vector-sized-1.0.0.0
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
