flags: {}
extra-package-dbs: []
packages:
- core
- geometry
- probability
- simulation
- cognition
- datasets
- neural-circuits
resolver: lts-10.6
ghc-options:
    "$locals": -Wall
    "$targets": ""
    "$everything": ""
